FROM ruby:3.4.8-alpine

ARG BUILD_PACKAGES="build-base git"
ARG DEV_PACKAGES="ruby-dev libffi-dev libxml2-dev libxslt-dev yaml-dev postgresql-dev nodejs npm pnpm zlib-dev imagemagick-dev libwebp-dev libpng-dev tiff-dev gcompat"
ARG RUBY_PACKAGES="tzdata postgresql-client"

ARG REPLACE_CHINA_MIRROR="true"
ARG ORIGINAL_REPO_URL="dl-cdn.alpinelinux.org"
ARG MIRROR_REPO_URL="mirrors.ustc.edu.cn"
ARG RUBYGEMS_SOURCE="https://gems.ruby-china.com"
ARG NPM_REGISTRY="https://registry.npmmirror.com"
ARG APP_ROOT="/app"

ENV RAILS_ENV="test" \
    NODE_ENV="test" \
    BUNDLE_APP_CONFIG="/usr/local/bundle/config" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development" \
    BUNDLE_DEPLOYMENT="false" \
    BUNDLE_FROZEN="false" \
    RUBY_YJIT_ENABLE="true" \
    TZ="Asia/Shanghai"

RUN set -ex && \
    if [ "$REPLACE_CHINA_MIRROR" = "true" ]; then \
      sed -i "s/$ORIGINAL_REPO_URL/$MIRROR_REPO_URL/g" /etc/apk/repositories && \
      gem sources --add "$RUBYGEMS_SOURCE" --remove https://rubygems.org/ && \
      bundle config mirror.https://rubygems.org "$RUBYGEMS_SOURCE"; \
    fi && \
    apk --update --no-cache add $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES && \
    if [ "$REPLACE_CHINA_MIRROR" = "true" ]; then \
      pnpm config set registry "$NPM_REGISTRY"; \
    fi

WORKDIR $APP_ROOT

COPY Gemfile Gemfile.lock ./
RUN set -ex && \
    BUNDLER_VERSION="$(awk '/BUNDLED WITH/{getline; gsub(/^[ \t]+|[ \t]+$/, ""); print}' Gemfile.lock)" && \
    gem install bundler -v "$BUNDLER_VERSION" && \
    bundle config set path "$BUNDLE_PATH" && \
    bundle config set without "$BUNDLE_WITHOUT" && \
    bundle config set force_ruby_platform true && \
    bundle lock --add-platform ruby && \
    bundle install --jobs "$(getconf _NPROCESSORS_ONLN)" --retry 3

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . $APP_ROOT
RUN SECRET_KEY_BASE=test bin/rails vite:build

CMD ["sh", "-lc", "bin/rails db:drop db:create db:schema:load && bundle exec rspec"]
