.git
.github
.cursor
.vscode

.bundle
node_modules
vendor/bundle
log
tmp
doc

public/assets
public/packs
public/uploads
public/system
public/vite-dev
public/vite-test

config/master*.key
config/credentials.yml*
config.env
.*env

db/*.sqlite3
db/*.sqlite3-journal

.DS_Store
.byebug_history
.history

Dockerfile*
!Dockerfile.test
!Dockerfile.test.dockerignore
